### ISSUE TITLE
Usage in embedded scenario (Wordpress Plugin Application)

### ISSUE THREAD

**Issue by RobIsHere** [thefrontside/emberx-file-input#34]
I'm using this in an embedded scenario inside of our video editor wordpress plugin.

The wordpress css is leaking in and adding borders around the hidden file input. So i added:
```css
.x-file--input {
    width: 1px;
    padding: 0 !important;
    margin: 0 !important;
}
```
Maybe you could apply this in your styles to have this "worry free developer"-experience ;)
